services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    command: ["--replSet", "dbrs", "--bind_ip_all"]
    volumes:
      - mongodb-data:/data/db
      - ./.docker/mongodb/rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
    networks:
      - digitowltest

networks:
  digitowltest:

volumes:
  mongodb-data:
